### ISSUE TITLE
Optionally track controller and action

### ISSUE THREAD

**Issue by adamthehutt** [ankane/exceptional-php#3]
Exceptional uses the controller and action parameters as part of the data it uses to group exceptions. For this and other reasons, it would be nice to be able to track that information when applicable. I've made a few small changes (quasi-diff below) to support this, which you might consider adding to the official distribution. With this change, one can simply assign Exceptional::$controller and/or Exceptional::$action to have that data passed along to the service.

```
exceptional.php: 
+    static $controller = "";
+    static $action = "";

exceptional/exceptional/data.php:
         $data["request"] = array(
             "url" => "$protocol$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]",
-            "controller" => "",
-            "action" => "",
+            "controller" => Exceptional::$controller,
+            "action" => Exceptional::$action,
             "parameters" => $params,
             "request_method" => strtolower($_SERVER["REQUEST_METHOD"]),
             "remote_ip" => $_SERVER["REMOTE_ADDR"],
```

**Comment by ankane** [comment]
Great suggestion Adam!  It's been added to the latest commit.

**Comment by tjchambers** [comment]
In researching another issue I noted that my $controller was not being passed to Exceptional. Turns out while the and/or was mentioned in the issues above, implementation of this require BOTH ACTION AND CONTROLLER to be specified. Specifying one without the other does not pass either. 

It seems logical that this should allow passing either $controller or $action individually if either are set. I say this because I am using them as a tracking device for the package the error originated from and only need one set (could set the other with a dummy value but...).
